### ISSUE TITLE
不再屏蔽kafan？

### ISSUE THREAD

**Issue by imba-tjd** [cobaltdisco/Google-Chinese-Results-Blocklist#12]
我猜是因为“卡饭教程”。现在`kafan.cn/topic`已经404了，它们应该移除掉这个功能了。
当然，本列表是阁下维护的，feel free to won't fix.

**Comment by cobaltdisco** [comment]
好的，我先自己试一段时间看看。

**Comment by cobaltdisco** [comment]
已经移除。

**Comment by imba-tjd** [comment]
GHHbD_perma_ban_list.txt 里的也请删掉吧 :joy:

**Comment by cobaltdisco** [comment]
发现列表同步有点问题，感谢提醒，已经移除。
