### ISSUE TITLE
这些赌博网站已经不做人了

### ISSUE THREAD

**Issue by tup2339** [cobaltdisco/Google-Chinese-Results-Blocklist#122]
我屏蔽了赌博网站的名字,结果这些网站用谐音污染我的搜索.
![20220905164042](https://user-images.githubusercontent.com/39553367/188408133-a93e27ab-2999-4156-8ea9-243a6f86a724.png)
![20220905164807](https://user-images.githubusercontent.com/39553367/188408453-8fe8df48-eada-48fa-a0f4-9fc5ee0e4bae.png)

**Comment by tup2339** [comment]
有什么方法屏蔽谐音字吗?

**Comment by kurikomoe** [comment]
这些网站的 title 都有格式，直接按格式走正则统一封杀叭

以这个为例子：
```regex
人名查询:[ ]?.*(姓名|创始人)是(什么|谁)？-
```
