### ISSUE TITLE
看楼主不更新我就自己fork了一个 

### ISSUE THREAD

**Issue by chaojibeian** [cobaltdisco/Google-Chinese-Results-Blocklist#124]
看楼主不更新我就自己fork了一个
https://github.com/chaojibeian/Google-Chinese-Results-Blocklist-update/blob/master/uBlacklist_subscription.txt

**Comment by dogeow** [comment]
太难了，这个贡献者写了这么多 (https://github.com/cobaltdisco/Google-Chinese-Results-Blocklist/pull/100)

**Comment by dogeow** [comment]
> 看楼主不更新我就自己fork了一个 https://github.com/chaojibeian/Google-Chinese-Results-Blocklist-update/blob/master/uBlacklist_subscription.txt

你也跑路了吗？

**Comment by chaojibeian** [comment]
我看错以为停更了，原来还有更新

**Comment by sgf** [comment]
fork 呢? 不能坚持.还搞啥fork
