### ISSUE TITLE
有什么办法可以屏蔽百度中的链接？？？

### ISSUE THREAD

**Issue by yangjingchuang** [cobaltdisco/Google-Chinese-Results-Blocklist#17]

**Comment by tjsky** [comment]
用这个脚本：
【AC-baidu-重定向优化百度搜狗谷歌必应搜索】https://greasyfork.org/zh-CN/scripts/14178
![image](https://user-images.githubusercontent.com/7272911/108645931-5232d180-74ef-11eb-9c5f-1bef5b4e3675.png)

在任意百度谷歌等的搜索结果页，点页面右上角的【自定义】勾选【附加2-自主拦截域名】点【DIY】在【编辑模式】下
将作者提供的用于【Google Hit Hider by Domain】的域名列表复制粘贴进来。确定保存即可。

百度谷歌必应鸭鸭里这些站点都会被屏蔽了，完美。

建议作者增加这种方式

**Comment by yangjingchuang** [comment]
> 用这个脚本：
> 【AC-baidu-重定向优化百度搜狗谷歌必应搜索】https://greasyfork.org/zh-CN/scripts/14178
> ![image](https://user-images.githubusercontent.com/7272911/108645931-5232d180-74ef-11eb-9c5f-1bef5b4e3675.png)
> 
> 在任意百度谷歌等的搜索结果页，点页面右上角的【自定义】勾选【附加2-自主拦截域名】点【DIY】在【编辑模式】下
> 将作者提供的用于【Google Hit Hider by Domain】的域名列表复制粘贴进来。确定保存即可。
> 
> 百度谷歌必应鸭鸭里这些站点都会被屏蔽了，完美。
> 
> 建议作者增加这种方式

好的，我先试下，谢谢了

**Comment by cobaltdisco** [comment]
> 用这个脚本：
> 【AC-baidu-重定向优化百度搜狗谷歌必应搜索】https://greasyfork.org/zh-CN/scripts/14178
> ![image](https://user-images.githubusercontent.com/7272911/108645931-5232d180-74ef-11eb-9c5f-1bef5b4e3675.png)
> 
> 在任意百度谷歌等的搜索结果页，点页面右上角的【自定义】勾选【附加2-自主拦截域名】点【DIY】在【编辑模式】下
> 将作者提供的用于【Google Hit Hider by Domain】的域名列表复制粘贴进来。确定保存即可。
> 
> 百度谷歌必应鸭鸭里这些站点都会被屏蔽了，完美。
> 
> 建议作者增加这种方式

感谢，已经添加。

**Comment by cobaltdisco** [comment]
没有更多回复，关闭该 Issue。
