### ISSUE TITLE
补充一些规则

### ISSUE THREAD

**Issue by entr0pia** [cobaltdisco/Google-Chinese-Results-Blocklist#18]
\*://www.hotbak.net/*
\*://www.9999ktv.com/*
\*://gnews.org/*
\*://m.dingjisc.com/*
\*://www.bolingtuan.com/*
\*://shufadashi.com/*
\*://www.dannypets.com/*
\*://www.guzhifa.com/*
\*://tiku.link/*
\*://app.51xuexiaoyi.com/*
\*://www.wenjingwudao.com/*
\*://blog.haishengship.com/*
\*://www.xinnet.com/*
\*://nethelpdesk.cn/*
\*://www.webplus.org.cn/*
\*://scikitlearn.com.cn/*
\*://sklearn.apachecn.org/*
\*://\*.bendibao.com/*
\*://www.fashion-high.net/*
\*://www.xiezuola.com/*
\*://www.yxjdcc.com/*
\*://www.53kr.com/*
\*://www.xsj2188.com/*

**Comment by mindfocus** [comment]
scikitlearn.com.cn
www.xinnet.com
这都不至于吧

**Comment by entr0pia** [comment]
> scikitlearn.com.cn
> [www.xinnet.com](http://www.xinnet.com)
> 这都不至于吧

![image](https://user-images.githubusercontent.com/30486766/108686041-d86f0800-752f-11eb-9b24-47db6e784d62.png)
sklearn的这个第三方中文站会引流到微信公众号, 我觉得很垃圾.
sklearn.apachecn.org的确误会了.

www.xinnet.com似乎是个spam站, 不记得搜什么的时候收集的了.
