### ISSUE TITLE
添砖加瓦

### ISSUE THREAD

**Issue by mindfocus** [cobaltdisco/Google-Chinese-Results-Blocklist#22]
www.it1me.com
www.voidcn.com
www.bbsmax.com
www.it1352.com
www.answiz.com
qastack.cn
stackoom.com
www.stacknoob.com
www.codercto.com
www.coder.work
www.codenong.com
stackoverrun.com
www.thinbug.com
www.itranslater.com
answer-id.com
www.itdaan.com
www.soinside.com
www.yuanmacha.com

**Comment by if1y** [comment]
www.11st22.com

**Comment by mxi1** [comment]
嗯，提得好！ 我刚刚搜到一个coder.work的机器翻译，想提个issue来更新列表呢。。

**Comment by guoxiao** [comment]
www.itranslater.com
uwenku.com

**Comment by cobaltdisco** [comment]
c9275b011469b469c2602da739f21923e97881c0

感谢，已经更新。

以及由于 uwenku.com 与 it1me.com 已无法访问，并未加入黑名单。

**Comment by mindfocus** [comment]
刚看到已经更新了，真棒
另：uwenku.com的首页www可以访问，未带www才无法访问

**Comment by cobaltdisco** [comment]
> 刚看到已经更新了，真棒
> 另：uwenku.com的首页www可以访问，未带www才无法访问

eae394c97ca8593a002b6c48a99496f8b246e569

感谢，已经更新。
