### ISSUE TITLE
请求添加spam网站

### ISSUE THREAD

**Issue by a342191555** [cobaltdisco/Google-Chinese-Results-Blocklist#27]
Spam 网页: https://www.cnpython.com/qa/426477
机翻来源: https://stackoverflow.com/questions/54980698/rpyc-asyncresulttimeoutresult-expired

**Comment by cobaltdisco** [comment]
请问是只有QA栏目有机翻，还是整个网站是机翻？我看了似乎还是有一些非机翻的内容。

**Comment by a342191555** [comment]
感觉QA栏目应该全是机翻
其它栏目可能不是

**Comment by cobaltdisco** [comment]
感谢。

*//www.cnpython.com/qa/* 已经添加。
