### ISSUE TITLE
有无使用hosts文件屏蔽方法

### ISSUE THREAD

**Issue by Viemean** [cobaltdisco/Google-Chinese-Results-Blocklist#28]
电脑上是舒服了，发现手机上体验依旧很差，然而手机上chrome又不能装插件。
所以问问能不能转成hosts文件方式屏蔽

**Comment by cobaltdisco** [comment]
恐怕是没有，以及我理解hosts文件方式也屏蔽不了搜索结果。

**Comment by imba-tjd** [comment]
你可以用uBO订阅GHHbD_perma_ban_list.txt的raw，不能屏蔽搜索结果，不过点进去后能显示屏蔽了

**Comment by Lehmaning** [comment]
hosts文件没法隐藏搜索结果。
