### ISSUE TITLE
屏蔽以 m. 开头的手机页面

### ISSUE THREAD

**Issue by bcaso** [cobaltdisco/Google-Chinese-Results-Blocklist#46]
正则：`/(m\.).*/`

`m.` 开头的多为手机页面，新闻页啥的

**Comment by mtgq** [comment]
> /(m\.).*/

好像这个正则有误杀，比方说测试的时候有这个网址 https://www.tianyuefangchan.com/mobile/sitemap/index-htm-mid-14-letter-m.html ，但是也会被 block掉

**Comment by bcaso** [comment]
试试这个：`/^https:\/\/m\./`

已测试，可屏蔽：https://m.uber.com, https://m.weibo.cn

保留：https://www.3m.com,

**Comment by bcaso** [comment]
> > /(m.).*/
> 
> 好像这个正则有误杀，比方说测试的时候有这个网址 https://www.tianyuefangchan.com/mobile/sitemap/index-htm-mid-14-letter-m.html ，但是也会被 block掉
试试这个：`/^https:\/\/m\./`

已测试，可屏蔽：https://m.uber.com, https://m.weibo.cn

保留：https://www.3m.com

**Comment by mtgq** [comment]
> > > /(m.).*/
> > 
> > 
> > 好像这个正则有误杀，比方说测试的时候有这个网址 https://www.tianyuefangchan.com/mobile/sitemap/index-htm-mid-14-letter-m.html ，但是也会被 block掉
> 
> 试试这个：`/^https?:\/\/m\./`
> 
> 已测试，可屏蔽：https://m.uber.com, https://m.weibo.cn
> 
> 保留：https://www.3m.com
> 
> https://regexper.com/#%5Ehttps%3F%3A%5C%2F%5C%2Fm%5C.
> ![image](https://user-images.githubusercontent.com/32212684/132102494-369fdb79-6d76-4e96-beee-43200dfe0fe0.png)

这个没问题，大佬牛批

**Comment by bcaso** [comment]
手机页面，还有以 wap. 开头的，规则是：`/^https?:\/\/wap\./`

如：zol 问答：https://wap.zol.com.cn/ask/details_2466034_2482161_3.html

**Comment by mtgq** [comment]
> 手机页面，还有以 wap. 开头的，规则是：`/^https?:\/\/wap\./`
> 
> 如：zol 问答：https://wap.zol.com.cn/ask/details_2466034_2482161_3.html
> 
> 还有以 3g. 开头的，规则是：`/^https?:\/\/3g\./`
> https://3g.163.com/dy/article/EG9RIKD905315FR9.html
> 这个可能有误杀

我发现，网址中带数字的一般大部分都是垃圾站，例如 aaa.123x.com 等等，像这种网址
