### ISSUE TITLE
类似列表

### ISSUE THREAD

**Issue by gyli** [cobaltdisco/Google-Chinese-Results-Blocklist#5]
我在维护一份类似的列表 https://github.com/gyli/Blocklist/blob/master/README.zh-cn.md

写了一些稍微自动化的脚本，所以条目多一些。希望对你有用。

**Comment by ausdruck** [comment]
这些 spam 站点大部分来源于搜索引擎爬虫算法自身漏洞，有兴趣听可以跟你解释下漏洞如何导致大量 spam 网站出现在搜索引擎里面。

**Comment by gyli** [comment]
@ausdruck 愿闻其详

**Comment by ausdruck** [comment]
**爬虫抓取过程:** 
1. 爬虫随机爬取到 spam 站点 a 页面 = s/a;
2. s/a 有 s/b 超链接;
3. 爬虫继续抓取 s/b，同样 s/b 有 s/a 超链接，结束;

**爬虫算法漏洞:**
1. 爬虫开始抓取 s/a，发现 s/b 超链接;
2. 爬虫继续抓取 s/b，发现 s/a1 超链接;
3. 爬虫继续抓取 s/a1, 发现 s/b1 超链接;
4. 爬虫继续抓取 s/b1, 发现 s/a2 超链接;
....

**case:**
1. 我 = s/a，你 = s/b;
2. 我是 = s/a1, 你是 = s/b1;
3. 我是谁 = s/a2, 你是谁 = s/b2;
4. 谁是我 = s/a3, 谁是你 =s/b3;
5. 是谁我 =spam, 是谁你 =spam;
6. 谁我是 = spam, 谁你是 = spam;
...
