### ISSUE TITLE
正则匹配，规则分组及其他

### ISSUE THREAD

**Issue by kurikomoe** [cobaltdisco/Google-Chinese-Results-Blocklist#56]
推荐正则采用 `^...$` 的方式。

```regex
title/^.*-\s*..(百科|知识)\s*网$/
title/^小.(百科|知识)网$/
title/^.小(百科|知识)网$/
```

Examples:
```
// 针对 `balabala - xx知识网` 这种格式
title/^.*-\s*..(百科|知识)\s*网$/    

// 针对直接就是 `小x知识网` 这种形式
title/^小.(百科|知识)网$/          
title/^.小(百科|知识)网$/
```

另外希望能把正则匹配规则，url 匹配规则等单列出来。

最后附上咱自己积累的一个规则列表，全是自己用 Google 的时候手动添加的：

https://raw.githubusercontent.com/kurikomoe/KurikoRulesets/master/ublacklist.txt

**Comment by entr0pia** [comment]
我直接```title/.*小.(百科|知识)网.*/```, 简单粗暴

**Comment by tjsky** [comment]
你测试加$有效吗？
我测试的插件只响应了^，对$不会响应。

**Comment by entr0pia** [comment]
> 你测试加有效吗？我测试的插件只响应了，对有效吗？ 我测试的插件只响应了^，对不会响应。

不需要限制位置啊, 全局范围内匹配到直接屏蔽就行了

**Comment by kurikomoe** [comment]
我测试是有效的：

测试：检查 $ 会不会影响到匹配结果。

1. 正样本
```
title/^.*-\s*..(百科|知识)\s*网$/
title/^小.(百科|知识)网$/
title/^.小(百科|知识)网$/
```
![image](https://user-images.githubusercontent.com/31176859/136651999-2ed6484a-8be5-447b-bc8b-63c14137d2a7.png)

2. 负样本（去掉`网`）

```
title/^.*-\s*..(百科|知识)\s*$/
title/^小.(百科|知识)$/
title/^.小(百科|知识)$/
```
![image](https://user-images.githubusercontent.com/31176859/136652052-7ca5d36f-0b7f-4248-8849-a52c994adaf3.png)

**Comment by kurikomoe** [comment]
> > 你测试加有效吗？我测试的插件只响应了，对有效吗？ 我测试的插件只响应了 ^，对不会响应。
> 
> 不需要限制位置啊，全局范围内匹配到直接屏蔽就行了

从广泛订阅的公有 rules 来讲，应该尽可能地精确匹配；全局只要出现特定模式的这种容易造成误伤，而且一旦出现误伤会波及到很多人。

**Comment by entr0pia** [comment]
> > > 你测试加有效吗？我测试的插件只响应了，对有效吗？ 我测试的插件只响应了 ^，对不会响应。
> > 
> > 
> > 不需要限制位置啊，全局范围内匹配到直接屏蔽就行了
> 
> 从广泛订阅的公有 rules 来讲，应该尽可能地精确匹配；全局只要出现特定模式的这种容易造成误伤，而且一旦出现误伤会波及到很多人。

学习了

**Comment by tjsky** [comment]
我当时没加 ^是因为有些抓取站会二次抓这些某某百科网，但是标题没修改成他自己的，导致实际页面标题是“含有”而不是“匹配”`balabala - xx知识网` 这种格式的尴尬情况，测试了下也没什么误杀。不过二次抓取的这种情况不多见。用你的规则，再用域名屏蔽其他二次抓取站貌似也挺好😊

**Comment by kurikomoe** [comment]
> Hi @kurikomoe，
> 
> 不知道“另外希望能把正则匹配规则，url 匹配规则等单列出来”的原因是？是觉得之后调整规则会相对容易？

正则的杀伤力比较大，分开一方面方便用户选择是否用正则匹配（普通规则，强力规则），另一方面感觉比较有条理一些。

**Comment by kurikomoe** [comment]
> Hi @kurikomoe @tjsky
> 
> 目前看来：
> 
> 1. `title/^小.(百科|知识)网$/` 来代替 `title/小.(百科|知识)网/` 来降低误杀，会进行规则更新。
> 2. `title/^.小(百科|知识)网$/` 匹配的是 X 小百科、知识网，似乎没有必要？
> 3. `title/^.*[ ]-[ ]小.(百科|知识)网$/` 来代替 `title/.* - 小.(百科|知识)网/`，不过有个疑问，为什么是要用 `[ ]` 来代替空格？

因为单纯的空格可读性有点低 `a b` vs `a[ ]b`。

我自己写正则习惯性的空格用 `[ ]` 来代替，防止键入和以后读正则的时候忘记这里有一个空格。
