### ISSUE TITLE
小*百科网（知识网）系列出现了新的马甲，请求添加

### ISSUE THREAD

**Issue by anyin233** [cobaltdisco/Google-Chinese-Results-Blocklist#58]
![Snipaste_2021-10-09_20-33-54.png](https://i.loli.net/2021/10/09/zlYKojtq7IgGVvw.png)

**Comment by cobaltdisco** [comment]
你好，请问对应的关键字是？

**Comment by entr0pia** [comment]
```title/.*- ?\S+(百科|知识)网/```
