### ISSUE TITLE
搜索关键字 “  六旬农民办低保发现“被上班” 月薪3500元  ”我遇到了全是菠菜网站，希望开发者添加列表。

### ISSUE THREAD

**Issue by Butterflyflower** [cobaltdisco/Google-Chinese-Results-Blocklist#60]
![Screenshot_20211010-191959](https://user-images.githubusercontent.com/67359838/136693447-d3faf71d-ce8c-4a95-86bb-c01077f5026a.png)
![Screenshot_20211010-181527](https://user-images.githubusercontent.com/67359838/136693454-ff190fe7-0a34-4571-8bf3-9a09c2402af6.png)

**Comment by Butterflyflower** [comment]
应该是扒的新浪新闻的标题

**Comment by FishOrBear** [comment]
看起来应该屏蔽 彩票 棋牌这样的关键字

**Comment by Butterflyflower** [comment]
*://*.hy8899.cc/*
*://*.356ae.com/*
*://*.18caiba.com/*
*://*.0370hz.com/*
*://*.hycp063.com/*
*://*.0a3q.com/*
*://*.jxyxtx.com/*
*://*.3b9ab.com/*
*://*.zlq09.com/*
*://*.daigoupiggy.com/*
*://*.gzcardiacsurg.com/*
*://*.sqwudong.com/*
*://*.shhkhb.com/*
*://*.fjbnc.com/*
*://*.sznovalux.com/*
*://*.hongkongxzm.com/*
*://*.xaxem.com/*
*://*.sya66.com/*
*://*.3enfv3an.com/*
*://*.dghuigao.com/*
*://*.sdzbyzjx.com/*
*://*.ac590.com/*
*://*.kljfgj.com/*
*://*.jbshy.com/*
*://*.f0760.com/*
*://*.freyachina.com/*
*://*.86699796.com/*
*://*.hdgangqiu.com/*
*://*.huanyuxumu.com/*
*://*.f0579.com/*
*://*.renrengou1.com/*
*://*.storewes.com/*
*://*.egfoem.com/*
*://*.cybei.com/*
*://*.dtybnh.com/*
*://*.feijiangpack.com/*
*://*.aidehouse.com/*
*://*.guangdongecu.com/*
*://*.jinmeiss.com/*
*://*.yiyou3.com/*
*://*.jy7cyn.com/*
*://*.jinmeiguan.com/*
*://*.myqianfengdq.com/*
*://*.funnywed.com/*
*://*.hfxxgang.com/*
*://*.skmacau.com/*
*://*.longtengkaibo.com/*
*://*.jnhf888.com/*
*://*.hntece.com/*
*://*.jiayujiancai.com/*
*://*.jiayicaiyin.com/*
*://*.xmyt88.com/*
*://*.hnblooddisease.com/*
*://*.yytflm.com/*
*://*.amxpj000.com/*
*://*.045ddd.com/*
*://*.amxpj25.com/*
*://*.dcxhnj.com/*
*://*.qimei888.com/*
*://*.zrxhn.com/*
*://*.guangzhouecu.com/*
*://*.zhenchuyuan.com/*
*://*.123boma.com/*
*://*.hjjyimeipeixun.com/*
*://*.wumeiyoupin.com/*
*://*.easyzc.com/*
*://*.shcml.com/*
*://*.happyjyjt.com/*
*://*.cancer0086.com/*
*://*.jiajufenxiao.com/*
*://*.31379266.com/*
*://*.wxhgfl.com/*
*://*.bjsjzycb.com/*
*://*.zhengwangsuye.com/*
*://*.yuffz.com/*
*://*.zgbjzn.com/*
*://*.txcj188.com/*
*://*.ycltgy.com/*
*://*.zgnzwzzgys.com/*
*://*.ynrjw.com/*
*://*.jmjiedai.com/*
*://*.derenlease.com/*
*://*.jskf999.com/*
*://*.fgmnr.com/*
*://*.8ld8.com/*
*://*.qdjjldaigou.com/*
*://*.ayhbte168.com/*
*://*.jpzdz.com/*
*://*.hkprimus.com/*
*://*.xzzflower.com/*
*://*.czsjsb.com/*
*://*.zibolongmoo.com/*
*://*.gzguanghan.com/*
*://*.haiyuesm.com/*
*://*.ahm7.com/*
*://*.ai46.com/*
*://*.kliwei.com/*
*://*.hnxel.com/*
