### ISSUE TITLE
uBlacklist可与自动翻页扩展uAutoPagerize共存

### ISSUE THREAD

**Issue by youkoulc** [cobaltdisco/Google-Chinese-Results-Blocklist#65]
现用翻页插件与uBlacklist有冲突的用户可选用此插件。
传送门：https://chrome.google.com/webstore/detail/uautopagerize/kdplapeciagkkjoignnkfpbfkebcfbpb/related?hl=en

既然有不少人都遇到这个问题，作者可以选择将这扩展写进教程以作提示。

**Comment by cobaltdisco** [comment]
不好意思，这个不会加入，无法保证接下来这两个插件是否不会冲突。
