### ISSUE TITLE
"XX搜" 之类的垃圾站

### ISSUE THREAD

**Issue by entr0pia** [cobaltdisco/Google-Chinese-Results-Blocklist#69]
检索词: ```天斧100zx```
网站举例:
```
*://jssou.cc/*
*://ysou.cc/*
*://chaosou.cc/*
*://sounote.cc/*
*://ksou.cc/*
```
屏蔽规则: ```title/^.*[ ]-[ ].{1,2}搜$/```

![image](https://user-images.githubusercontent.com/30486766/138050674-ff99a49b-46e7-43c8-a5f2-1640c6ac4f3e.png)

**Comment by cobaltdisco** [comment]
感谢，网页会加入名单，标题匹配方式暂不会加入。
