### ISSUE TITLE
add sites

### ISSUE THREAD

**Issue by arandintday** [cobaltdisco/Google-Chinese-Results-Blocklist#71]
```
*://bifentuijian.swiftbn.com/*
*://xinfx.cc/*
*://m.18183.com/*
*://m.qishh.com/*
*://m.tabuzhe.com/*
*://xindd.cc/*
*://taofx.cc/*
*://yifx.cc/*
*://www.youchuang365.com/*
*://sunnews.cc/*
```
其中xin***.cc和***fx.cc疑似为新的中文SEO站群

**Comment by cobaltdisco** [comment]
Hi，

以下网址将会被添加：

```
*://*.swiftbn.com/*
*://*.xinfx.cc/*
*://*.xindd.cc/*
*://*.taofx.cc/*
*://*.yifx.cc/*
*://*.www.youchuang365.com/*
*://*.sunnews.cc/*
```

以下网址已经无法访问：

```
*://*.qishh.com/*
*://*.tabuzhe.com/*
```

以下网址看似正常：

`*://*.18183.com/*`

**Comment by woyjuq** [comment]
*://m.nas-portal.com/*
*://www.yirenkeji.com/*
 title/.*爱赢/
 title/.*赌博/
*://m.sycwsdp.com/*
*://www.i4k.xyz/*
*://www.sohu.com/*
*://toutiao.io/*
*://programmerall.com/*

**Comment by cobaltdisco** [comment]
> _://m.nas-portal.com/_ _://www.yirenkeji.com/_ title/.*爱赢/ title/.*赌博/ _://m.sycwsdp.com/_ _://www.i4k.xyz/_ _://www.sohu.com/_ _://toutiao.io/_ _://programmerall.com/_

Hi @woyjuq 

以下规则将被添加：

```
*://*.nas-portal.com/*
*://*.yirenkeji.com/*
*://*.sycwsdp.com/*
*://*.i4k.xyz/*
*://*.programmerall.com/*
```

以下规则不会添加 (误杀或因为是大网站官网)：

```
*://*.sohu.com/*
*://*.toutiao.io/*
title/.*爱赢/
title/.*赌博/
```
