### ISSUE TITLE
new sites

### ISSUE THREAD

**Issue by PlexPt** [cobaltdisco/Google-Chinese-Results-Blocklist#73]
![image](https://user-images.githubusercontent.com/15922823/138628906-208cbee5-b2eb-445f-aa60-b3bf19dcc1c7.png)

**Comment by bcaso** [comment]
新的垃圾站

*://tw511.com/*
*://www.pudish.me/*

**Comment by bcaso** [comment]
*://edu.xiaobenzi.com/*

**Comment by cobaltdisco** [comment]
@PlexPt 如 bcaso 所说，规则已经覆盖。

@bcaso 感谢，会加入列表。
