### ISSUE TITLE
新的垃圾站

### ISSUE THREAD

**Issue by iamjing66** [cobaltdisco/Google-Chinese-Results-Blocklist#77]
类似 XX懶人包这样的网站
链接 [零售貼文懶人包](https://retailtagtw.com/results/43357b8c103169fb4845)

**Comment by bcaso** [comment]
这并非 XX懒人包，而是 (百科)|(知识网)

![image](https://user-images.githubusercontent.com/32212684/139519349-c9d43507-ef07-44cd-9f4a-44f7b7283cc8.png)

这种网站应该属于规则
```
        title/^小.(百科|知识)网$/
        title/^.*[ ]-[ ]小.(百科|知识)网$/
```
但是上面的两个，都有前后定界符，对这个地址不起作用，将其合并修改为 `title/(百科|知识)网/` 即可

**Comment by iamjing66** [comment]
> 这并非 XX懒人包，而是 (百科)|(知识网)
> 
> ![image](https://user-images.githubusercontent.com/32212684/139519349-c9d43507-ef07-44cd-9f4a-44f7b7283cc8.png)
> 
> 这种网站应该属于规则
> 
> ```
>         title/^小.(百科|知识)网$/
>         title/^.*[ ]-[ ]小.(百科|知识)网$/
> ```
> 
> > https://github.com/cobaltdisco/Google-Chinese-Results-Blocklist/blob/master/uBlacklist_match_patterns.txt
> > 第 7，8 行
> 
> 但是上面的两个，都有前后定界符，对这个地址不起作用，将其合并修改为 `title/(百科|知识)网/` 即可

好的，谢谢
