### ISSUE TITLE
编程猎人垃圾站

### ISSUE THREAD

**Issue by ymyguang** [cobaltdisco/Google-Chinese-Results-Blocklist#78]
https://www.programminghunter.com

**Comment by bcaso** [comment]
代码聚合站：
*://codeantenna.com/*

**Comment by bcaso** [comment]
pythonmana.com

**Comment by bcaso** [comment]
www.mamicode.com

**Comment by bcaso** [comment]
https://www.chinarealwax.com/

**Comment by bcaso** [comment]
https://www.51ajia.com/

**Comment by bcaso** [comment]
`*://www.cuiweiju.com/*`

**Comment by bcaso** [comment]
`*://cdmana.com/*`

**Comment by ymyguang** [comment]
以上已整理，并申请提交合并

**Comment by bcaso** [comment]
https://tbbee.cc/jfx/84b788ddedd1d9a9bed2a2e88d8bda80e8d1dcf8bed3fbb482b98f8282f6.html

**Comment by cobaltdisco** [comment]
Hi @bcaso @ymyguang，

感谢，已经添加。但的确比较难添加。
