### ISSUE TITLE
支持ublock

### ISSUE THREAD

**Issue by 20NE** [cobaltdisco/Google-Chinese-Results-Blocklist#79]
希望能支持 [ublock origin](https://github.com/gorhill/uBlock#ublock-origin)
谢谢

**Comment by bcaso** [comment]
这两个有冲突吗？uBlacklist 与 ublock origin 就没有关系吧？作用范围也不同。: )

**Comment by 20NE** [comment]
ublock origin  也可過濾google搜索結果 https://www.reddit.com/r/uBlockOrigin/comments/dzjogk/can_you_somehow_remove_sites_from_google_search/

**Comment by bcaso** [comment]
> 希望能支持 [ublock origin](https://github.com/gorhill/uBlock#ublock-origin)
> 谢谢

搜索结果过滤规则是插件uBlacklist的作者定的，这个插件仅作用于搜索结果，与广告屏蔽插件实现可能方式不同。

至于广告蔽插件与搜索结果过滤插件的规则是否能兼容，应该反馈给插件开发者，而不是这里。

**Comment by 20NE** [comment]
好，关了
