### ISSUE TITLE
new site

### ISSUE THREAD

**Issue by rojunghwa** [cobaltdisco/Google-Chinese-Results-Blocklist#82]
*://www.626927.com/*
*://www.nanshansi123.com/*
*://www.kny598.com/*

**Comment by syaoo** [comment]
*://*.4000202123.com/*
*://*.npx85.com/*

**Comment by cobaltdisco** [comment]
Hi @syaoo @rojunghwa 

以下网址将会被添加：

`*://*.626927.com/*`

以下网址已经无法访问：

```
*://*.kny598.com/*
*://*.4000202123.com/*
*://*.npx85.com/*
```

以下网址看似正常：

`*://*.nanshansi123.com/*`

**Comment by rojunghwa** [comment]
*://*paaqjs.com/*

**Comment by AkizoraMineko** [comment]
://dc0714.com
://08rqt.com
://52dcr.com
ww.xtwlyy.com
ww.czag88.com

**Comment by bcaso** [comment]
http://zhuantiyi.com/51c99df7c4a3.html

**Comment by cobaltdisco** [comment]
Hi @AkizoraMineko @bcaso 

以下网址将会被添加：

`*://*.zhuantiyi.com/*`

以下网址已经无法访问：

```
*://*.dc0714.com/*
*://*.08rqt.com/*
*://*.52dcr.com/*
*://*.xtwlyy.com/*
*://*.czag88.com/*
```
