### ISSUE TITLE
Github 信息爬虫站

### ISSUE THREAD

**Issue by NeverBehave** [cobaltdisco/Google-Chinese-Results-Blocklist#92]
这类站点通常都是刷SEO，质量极差，占用搜索结果同时还不给出源站地址

- gitmemory.com
- githubmemory.com
- repoarchive.com
- giter.com

**Comment by cobaltdisco** [comment]
Hi，

感谢提供。前 3 个会加入，第四个域名已经无法访问，估不会加入。

**Comment by NeverBehave** [comment]
最后一个是 giters.com
