### ISSUE TITLE
新的搜索引擎，F 搜索

### ISSUE THREAD

**Issue by bcaso** [cobaltdisco/Google-Chinese-Results-Blocklist#95]
小众网站的介绍，https://www.appinn.com/f-search/

F 社区：https://nilmap.com/

看起来还在开发中，建议尝试下，可以多提下搜索过滤的要求 ：）

**Comment by bcaso** [comment]
如果这个引擎做到了搜索过滤，那么将可以很大一部分的替代谷歌。

**Comment by bcaso** [comment]
最近了解到，黑白名单可能存在法律问题。

如果 “F 搜” 最终做不出黑白名单，那么必应也是个不错的选择。速度快，免翻，可过滤。

**Comment by 4SM** [comment]
此乃天然阉割之物呀
