### ISSUE TITLE
分享乐子

### ISSUE THREAD

**Issue by whentojump** [cobaltdisco/Google-Chinese-Results-Blocklist#99]
2010年，脚本之家（本身就是个老SEO站了）发布了一则[站长公告](https://www.jb51.net/article/25566.htm)，说本站改了标题、描述什么的，~~以便于更好地SEO~~。

**7年后**，某某云如获至宝，把这则公告爬下来，翻成英文和港台式中文，发布在它的“社区”里面，其中一版为《[**指令碼之家**修改了網站標題與網站描述](https://topic.alibabacloud.com/tc/a/the-script-home-has-modified-the-website-title-and-description_8_8_32425402.html)》。

---

简单分享一下互联网大厂的体面，过段时间我自己关issue，积累了一定站点后会提PR:smiling_face_with_three_hearts:

**Comment by iDvel** [comment]
我想帮阿里云体面。
![image](https://user-images.githubusercontent.com/14658234/149563948-55c4715f-b174-4cf3-98c0-c0ac1102f631.png)

**Comment by Azimiao** [comment]
国内搜索引擎随便搜个什么东西满屏的都是 csdn、阿里云、腾讯云社区巴拉巴的，这就是大厂承担的社会责任么😀。
